name: Build and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: "17"
      - name: Install packages
        run: npm install
        working-directory: ./2-vue
      - name: Build application
        run: npm run build
        working-directory: ./2-vue
      - name: Deploy Github page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          publish_dir: ./2-vue/dist